#+TITLE: Chapter 3
#+AUTHOR: Amr Elsayed
#+BIBILOGRAPHY: library.bib 
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LaTeX_HEADER: \affiliation{<Your school, think tank, etc>}
#+LaTeX_HEADER: \shorttitle{<A short version of the long title for page headers>}
#+LaTeX_HEADER: \usepackage{breakcites}
#+LaTeX_HEADER: \usepackage{apacite}
#+LaTeX_HEADER: \usepackage{paralist}
#+LaTeX_HEADER: \let\itemize\compactitem
#+LaTeX_HEADER: \let\description\compactdesc
#+LaTeX_HEADER: \let\enumerate\compactenum

#+BEGIN_ABSTRACT

*Abstract*

#+END_ABSTRACT
#+LaTeX: \tableofcontents
* Histogram procesing
  we represent pictures using M x N pixels and each pixel has an integer value. and if you want to have general idea how the intensities is distriduted,we create histrogram
** TODO unnormalized histogram
** normalized histogram
** example about histograms
** TODO Histogram equalization
   equations
   coding part (Histo.py)
* Fundamentals of spatial filtering
The name filter is borrowed from frequency domain processing where “filtering” refers to passing, modifying,
or rejecting specified frequency components of an image. For example, a filter that passes low frequencies is called a lowpass filter.
The net effect produced by a lowpass filter is to smooth an image by blurring it. We can accomplish similar smoothing directly on the
image itself by using spatial filters.
Spatial filtering modifies an image by replacing the value of each pixel by a function of the values of the pixel and its neighbors. If the
operation performed on the image pixels is linear, then the filter is called a linear spatial filter. Otherwise, the filter is a nonlinear spatial
filter. We will focus attention first on linear filters and then introduce some basic nonlinear filters. 
** linear filtering
kernel
** image padding
** correlation and convolution
** Gaussian Filter
    A Gaussian filter is a linear filter. It's usually used to blur the image or to reduce noise. If you use two of them and subtract,
    you can use them for "unsharp masking" (edge detection).
    The Gaussian filter alone will blur edges and reduce contrast.
The Median filter is a non-linear filter that is most commonly used as a simple way to reduce noise in an image.
It's claim to fame (over Gaussian for noise reduction)
is that it removes noise while keeping edges relatively sharp.
I guess the one advantage a Gaussian filter has over a median filter is that it's faster because multiplying and adding is probably faster than sorting.
